# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jonas Tryggvi
tagline:             'my blog of all things'
description:         'This is my blog page, where I post my opinions on different things. My writings are both in English and Icelandic, so if you are suddently reading gibberish - then I am writing something intended for my fellow countrymen. '
url:                 http://jonastryggvi.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jónas Tryggvi
  url:               https://twitter.com/jonastryggvi
  email:             jonastryggvi@gmail.com

# Custom vars
version:             1.0.0
